# Generated by Django 2.2.6 on 2019-11-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
