# Generated by Django 2.2.6 on 2019-11-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.TextField(max_length=37),
        ),
    ]
