# Generated by Django 2.2.6 on 2019-11-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191103_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transaksi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
