# Generated by Django 2.2.6 on 2019-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='transaksi',
            field=models.CharField(max_length=400),
        ),
    ]
