# Generated by Django 2.2.6 on 2019-11-09 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191104_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.IntegerField(primary_key=True, serialize=False)),
                ('barang', models.CharField(max_length=400)),
                ('harga', models.CharField(max_length=400)),
                ('alamat', models.CharField(max_length=400)),
                ('ekspedisi', models.CharField(max_length=20)),
                ('pembayaran', models.BooleanField(default=False)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
