# Generated by Django 2.2.6 on 2019-11-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_transaksi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
