# Generated by Django 2.2.6 on 2019-11-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_transaksi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'User'},
        ),
    ]
