# Generated by Django 2.2.6 on 2019-11-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
