# Generated by Django 2.2.5 on 2019-10-16 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemuaJenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('warna', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('deskripsi', models.TextField()),
                ('tersedia', models.BooleanField()),
                ('dateUpdate', models.DateField(blank=True, null=True)),
                ('dateCreate', models.DateField(auto_now_add=True, null=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SemuaJenis')),
            ],
        ),
    ]
