# Generated by Django 2.2.5 on 2019-10-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemuaBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandAll', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='barang',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SemuaBrand'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='dateUpdate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
