# Generated by Django 2.2.5 on 2019-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191016_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semuabrand',
            old_name='brandAll',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='barang',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.SemuaBrand'),
        ),
    ]
