# Generated by Django 2.2.5 on 2019-10-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191016_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='warna',
            field=models.CharField(max_length=50),
        ),
    ]
