# Generated by Django 2.2.5 on 2019-10-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191016_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemuaBrand',
            new_name='SemuaBarang',
        ),
        migrations.RenameField(
            model_name='barang',
            old_name='brand',
            new_name='barang',
        ),
    ]
