# Generated by Django 2.2.5 on 2019-10-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20191018_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemuaBarang',
            new_name='SemuaBrand',
        ),
    ]
