# Generated by Django 2.2.5 on 2019-10-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20191022_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='barang',
            new_name='brand',
        ),
    ]
