# Generated by Django 2.2.6 on 2019-11-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20191022_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name_plural': 'Barang'},
        ),
        migrations.AlterModelOptions(
            name='semuabrand',
            options={'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='semuajenis',
            options={'verbose_name_plural': 'Jenis Barang'},
        ),
    ]
