# Generated by Django 2.2.6 on 2019-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20191110_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='terjual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
