# Generated by Django 2.2.6 on 2019-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_auto_20191104_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id_transaksi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
