# Generated by Django 2.2.6 on 2019-11-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0004_auto_20191104_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksi',
            options={'verbose_name_plural': 'Transaksi'},
        ),
    ]
