# Generated by Django 2.2.6 on 2019-11-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0005_auto_20191110_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='id_transaksi',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='pembayaran',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
