# Generated by Django 2.2.6 on 2019-11-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0009_auto_20191119_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='id_transaksi',
            field=models.CharField(blank=True, max_length=38, primary_key=True, serialize=False),
        ),
    ]
