# Generated by Django 2.2.6 on 2019-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0010_auto_20191119_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='detailHarga',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='harga',
            field=models.CharField(max_length=100),
        ),
    ]
