# Generated by Django 2.2.6 on 2019-11-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0011_auto_20191119_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='dateCreate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='dateUpdate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
